dynaconf_merge = true

[default.db]
uri = "sqlite:///database.db"
connect_args = { check_same_thread = false }

[default.time]
tz_name = "Europe/Berlin"

[default.about]
title = "minutes API"


[development.db]
echo = false

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:5173"]
host = "localhost"
port = "8000"
scheme = "http"

[production.db]
echo = false
