dynaconf_merge = true

#
# Defaults
#

[default.db]
uri = "sqlite:///database.db"
connect_args = { check_same_thread = false }

[default.time]
tz_name = "Europe/Berlin"

[default.server]
upload_dir = "uploads"

[default.about]
title = "minutes API"
contact = { name = "IDA", email = "idaBotHelp@gmail.com" }

#
# Development
#

[development.db]
echo = false

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:5173"]
host = "localhost"
port = "8000"
scheme = "http"

#
# Production
#

[production.db]
echo = false

[production.server]
log_level = "error"
reload = false
cors_origins = ["http://????:????"]
host = "0.0.0.0"
port = "8000"
scheme = "http"
