version: '3.4'
services:
    setup:
        image: alpine:latest
        volumes:
            - ./database:/mnt/setup
        command: >
            ash -c "touch /mnt/setup/database.db"
        restart: on-failure

    frontend:
        image: frontend
        build:
            context: ./../frontend
            target: deploy-static
        ports:
            - 5173:5173
        depends_on:
            - setup
            - backend
        volumes:
            - ./settings/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        # as the environment variables must be present during build time, you can't specify them here

    backend:
        image: backend
        build:
            context: ./../backend
        ports:
            - 8000:8000
        volumes:
            - ./database/database.db:/code/database.db
        depends_on:
            - setup
        restart: always
        environment:
            ENV_FOR_MINUTES: production # development
            # alternative to providing the .secrets.toml (see examples/) you can also set the environment variables here
            # all variables specified in .secrets.toml must have the prefix `minutes`
            # cf. for more information https://www.dynaconf.com/envvars/
            # e.g.:
            # minutes_server__cors_origins: http://localhost:5173
