version: '3.4'
services:
    minutes_setup:
        image: alpine:latest
        volumes:
            - ./database:/mnt/setup
        command: >
            ash -c "touch /mnt/setup/database.db"
        restart: on-failure

    minutes_frontend:
        build:
            context: ./../frontend
            target: deploy-static
        ports:
            - 5173:5173
        volumes:
            - ./settings/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        # as the environment variables must be present during build time, you can't specify them here

    minutes_backend:
        build:
            context: ./../backend
        ports:
            - 8000:8000
        volumes:
            - ./uploads:/code/uploads # cf. MINUTES_server__upload_dir
            - ./database/database.db:/code/database.db
        depends_on:
            - minutes_setup
        restart: always
        environment:
            ENV_FOR_MINUTES: production # development
            # override config.toml variables (use prefix `MINUTES`)
            # cf. https://www.dynaconf.com/envvars/
            MINUTES_server__cors_origins: http://localhost:5173
