dynaconf_merge = true

[default.db]
uri = "sqlite:///database.db"
connect_args = {check_same_thread=false}

[production.db]
echo = false

[default.server]
upload_dir = "uploads"
upload_path = "/uploads"


[default.about]
contact = {name="name", email="email@beispiel.com"}
